site_name: Boston Housing
#
site_author: datanalist@github.com
#
nav:
  - Главная: index.md
  - Начало работы: getting-started.md
  - Руководства:
      - Управление конфигурациями: guides/CONFIGURATION_MANAGEMENT.md
      - Docker: guides/DOCKER.md
      - Окружение: guides/ENV.md
      - Эксперименты: guides/EXPERIMENTS.md
      - Продвинутые эксперименты: guides/EXPERIMENTS-ADVANCED.md
      - MLflow + DVC + MinIO: guides/MLFLOW+DVC+MINIO.md
      - MinIO + DVC: guides/MINIO+DVC.md
      - Pre-commit хуки: guides/PRE-COMMIT.md
      - Интеграция трекинга: guides/TRACKING-INTEGRATION.md
      - Airflow ML Pipeline: guides/airflow_ml_pipeline.md

theme:
  name: readthedocs
  locale: ru
